#!/bin/sh
# This script is useful in tomcat operations
# create

if [[ -z "$CATALINA_HOME" || -z "$CATALINA_INSTANCE_HOME" ]]; then
    echo "CATALINA_HOME && CATALINA_INSTANCE_HOME need to be configured."
    exit 1
fi


showhelp () {
    echo "Usage: { start | stop | logs } $1"
    echo "    \$1 - Instance's Name"
}


case "$1"  in
'create')
    if [ -z "$2" ]; then
        showhelp
        RETVAL=1
    else
        APP_HOME=$CATALINA_INSTANCE_HOME/$2
        if [ -e $APP_HOME ]; then
            echo "The instance '$2' is exists."
            echo "Path: $APP_HOME"
            RETVAL=1
        else
            echo "Preparing Directory & Files..."
            mkdir $APP_HOME
            mkdir $APP_HOME/logs
            mkdir $APP_HOME/conf
            mkdir $APP_HOME/temp
            mkdir $APP_HOME/work
            mkdir $APP_HOME/webapps
            mkdir $APP_HOME/lib
            mkdir $APP_HOME/bin

            cp -rf $CATALINA_HOME/custom/bin/* $APP_HOME/bin
            cp -rf $CATALINA_HOME/custom/conf/* $APP_HOME/conf
            echo "Instance '$2' is created."
            RETVAL=0
        fi
    fi
    ;;
'start')
    export CATALINA_BASE=$CATALINA_INSTANCE_HOME/$2
    $CATALINA_HOME/bin/startup.sh
    RETVAL=0
    ;;
'stop')
    export CATALINA_BASE=$CATALINA_INSTANCE_HOME/$2
    $CATALINA_HOME/bin/shutdown.sh
    RETVAL=0
    ;;
'logs')
    tail -f $CATALINA_INSTANCE_HOME/$2/logs/catalina.out
    RETVAL=0
    ;;
'config')
    echo "CATALINA_HOME=$CATALINA_HOME"
    echo "CATALINA_INSTANCE_HOME=$CATALINA_INSTANCE_HOME"
    ;;
*)
    showhelp
    RETVAL=1
    ;;
esac



unset showhelp
exit $RETVAL
